spring.application.name=backend

# 1. Configuração do Banco de Dados H2 em Memória
spring.datasource.url=jdbc:h2:mem:clinicadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Habilitar o Console Web do H2 (para acessar a interface gráfica do banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# 3. Configurações do JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
